### ISSUE TITLE
Uncaught exception: Error: Header must provide a Content-Length property

### ISSUE THREAD

**Issue by mnmaraes** [neoclide/coc-rls#53]
coc-rls started returning this issue. Not sure what's going on. I've looked around seems to be an issue with the communication between coc and the language server. However none of these tools have changed in a while.

Any idea on what might going on?

```
[coc.nvim] error: Uncaught exception: Error: Header must provide a Content-Length property.                                                                                               
    at StreamMessageReader.onData (/Users/murillo/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)                                                          
    at Socket.<anonymous> (/Users/murillo/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)                                                                  
    at Socket.emit (events.js:210:5)                                                                                                                                                      
    at addChunk (_stream_readable.js:309:12)                                                                                                                                              
    at readableAddChunk (_stream_readable.js:290:11)                                                                                                                                      
    at Socket.Readable.push (_stream_readable.js:224:10)                                                                                                                                  
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23) 
```

**Comment by mnmaraes** [comment]
Figured it out. Had to cd into coc's config dir and rerun `yarn install`

**Comment by chemzqm** [comment]
You don't need `yarn install` when the extension is installed from `CocInstall` command.

**Comment by mnmaraes** [comment]
No. That actually wasn't the fix nor the source of the problem. The source seems to be the actual code I was writing, removing the macro I was developing and restarting `nvim` fixed it (which is why I thought `yarn install` had done it). Readding it, broke it again

**Comment by chemzqm** [comment]
Should be bug of your rls, checkout verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
